<?php

/**
 *  @file
 *  Custom settings
 *  (overrides default settings)
 *  @see engine/core/config/default_settings.inc
 */

//      Content Defaults
//$page_title = "Hello world";
//$metadata[ 'site_name' ] = "My Project";
//$metadata[ 'head_page_title' ] = $page_title .' — '. $metadata[ 'site_name' ];
//$metadata[ 'description' ] = "Description of my project";
//$metadata[ 'lang' ] = 'en';
//$metadata[ 'locale' ] = 'en_EN';
//$metadata[ 'timezone' ] = 'UTC';
//$html_attr[ 'lang' ] = $metadata[ 'lang' ];
//$body_attr[ 'class' ] = 'example-body-class';


//      Debug
//      Note : there's also krumo() or print kpr() for manual pretty-printed var dumps
//      @see engine/core/_debug.inc

//      Display Php errors
//$debug[ 'php' ] = 1;

//      Prints included files for current path
//$debug[ 'routing' ] = 1;

//      Prints included template files for current path
//$debug[ 'tpl' ] = 1;

//      Prints request array for current path
//$debug[ 'req' ] = 1;

//      (needs a tpl that prints $content)
//$debug[ 'exec_time' ] = 1;
